version: '3'

services:
  pelayocompose-pg:
    image: postgres
    container_name: pelayocompose-pg
    environment:
      POSTGRES_DB: pldiplomado_db2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - lab4-compose-network
    volumes:
      - lab4-compose-volumen:/var/lib/postgresql/data

  backend-compose-pl:
    image: luhpelayo/pldiplomadobackend
    container_name: backend-compose-pl
    environment:
      DB_PORT: 5432
      DB_HOST: pelayocompose-pg
      DB_USER: postgres
      DB_PASS: root
      DB_NAME: pldiplomado_db2
    ports:
      - "8800:8800"
    networks:
      - lab4-compose-network
    depends_on:
      - pelayocompose-pg

  frontend-compose-pl:
    image: luhpelayo/pldiplomadofrontend
    container_name: frontend-compose-pl
    environment:
      REACT_APP_API_URL: "http://localhost:8800/"
    ports:
      - "3000:3000"
    networks:
      - lab4-compose-network
    depends_on:
      - backend-compose-pl

networks:
  lab4-compose-network:
    driver: bridge

volumes:
  lab4-compose-volumen:
